### ISSUE TITLE
Update to use new 2.0.3 release of Powershell module

### ISSUE THREAD

**Issue by Swift-Financial** [voxpupuli/puppet-iis#131]
- [ ] Upgrade the [puppetlabs/powershell](https://forge.puppet.com/puppetlabs/powershell/changelog) dependency to the 2.0.1 release.
- [ ] Run acceptance tests
- [ ] Tag and release

**Comment by marcinbojko** [comment]
Second to that.

**Comment by igalic** [comment]
s/2.0.1/2.0.3/

**Comment by ferventcoder** [comment]
@bbriggs @bastelfreak Thoughts here?

**Comment by ferventcoder** [comment]
For installing `puppetlabs/windows`, this module is causing a fallback to the older powershell module.

**Comment by bbriggs** [comment]
@ferventcoder Can you explain that a little more?

I'd love to see this use a newer version of powershell, but I just wanna get a feel for things first.

**Comment by ferventcoder** [comment]
Sure. The Windows Module Pack is a collection of supported/approved modules that can all be installed with a single module install call - https://forge.puppet.com/puppetlabs/windows/readme

It's a metamodule designed to bring in other modules - https://forge.puppet.com/puppetlabs/windows/dependencies. I did some research after installing the latest release this morning and found that puppet-iis was the culprit of why I ended up with `puppetlabs/powershell` v1.0.6 instead of in the 2.x series.

By all means, I think proper testing is definitely necessary. Just curious if this is something that was on the radar for folks or not.

**Comment by petems** [comment]
@bbriggs So the old powershell implementation did every powershell call as individual calls, slowing down runs.

The new version consolidates into one run, speeding things up a lot.

I think if we run the acceptance tests and the new Powershell works, we can bump the Powershell dep followed by a major increment module bump?

**Comment by alexjfisher** [comment]
@petems Is a major version bump required?

puppet-msoffice has the same issue and I've just opened https://github.com/voxpupuli/puppet-msoffice/pull/34

**Comment by petems** [comment]
I mean, the Powershell stuff is potentially a breaking change, although the behaviour should be 1:1

**Comment by bbriggs** [comment]
Which OS versions (if any) would lose support as a result of this dependency bump?

**Comment by petems** [comment]
IIRC it would be the same on all supported Windows releases (2k8, 2k8+R2, 2012, 2012+R2).

In SemVer terms, we could no a minor bump, then fix any potential bugs with a tiny release as far as I understand? 

IMO bumping is cheap, and I'd go over cautious than under...

**Comment by bastelfreak** [comment]
Hi. I'm going to close this Issue. We deprecated the module and the new version is available here: https://forge.puppet.com/puppetlabs/iis
